[package]
name = "lan_clipboard_client"
version = "0.1.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
lan_clipboard = { path = "../" }
protobuf = "1.4"
clipboard = "0.4"
native-tls = "0.1"
chrono = "0.4"
