# Client config

# All values are preceded by whether they are required or optional. For any optional value,
# commenting or removing the line will leave that value unspecified. If an optional value is
# unspecified, it will use a default value, specified after a colon in the optional tag.

# All values are also mentioned if they can be overwritten with command-line arguments. If this is
# true, then values may be omitted in the same manner as an optional value, but they must be
# specified on the command-line.

[connection]
# (required, cli) The hostname of the server to connect to.
hostname = "localhost"
# (required, cli) The port of the server to connect to.
port = 38153
# (required, cli) The name to register with the server.
name = "OS name"
# (optional: false) Whether to attempt reconnection after being disconnected. This will not attempt
# a reconnect if a rejection message is sent by the server. If the server hangs up on the client,
# a reconnect will only occur if the hangup was for a ping timeout.
reconnect = false
# (optional: 15) The number of seconds to wait before attempting a reconnect. Has no effect if
# reconnects are not enabled.
reconnect_period = 15

[certificate]
# (required, cli) The certificate chain file location. This must match the chain the server is
# using.
file = "cert.pem"

[logging]
# (required) The level at which to log information. Messages of the specified level or higher will
# be printed, and those lower will be filtered out. The levels from lowest to highest are off,
# trace, debug, info, warn, or error. If you aren't sure what this should be, choose info.
level = "info"
# (optional: will not write to file) The file to write log messages to. Useful when in daemon mode.
# Note that this does not redirect stdout to the file. If you want to silence stdout and also write
# to the file, specify this value and use `> /dev/null` on the command line.
# file = "client.log"

[daemon]
# (optional: false, cli) Whether to use daemon mode. If true, the client will fork into the
# background.
# Note that daemon mode is not available on Windows.
enabled = false
# (optional: no PID file) The file to store the daemon's PID in.
pid_file = "client.pid"
# (optional: false) Whether to change the owner of the PID file to the user and group the daemon is
# running as.
chown_pid_file = false
# (optional: user that started process) The user to run the daemon as.
# user = 0
# (optional: group of user that started process) The group to run the daemon as.
# group = 0
