[package]
name = "lan_clipboard_server"
version = "0.1.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
lan_clipboard = { path = "../" }
protobuf = "1.4"
integer-encoding = "1.0"
rustls = "0.11"
mio = "0.6"
slab = "0.4"
webpki = "0.17"
untrusted = "0.5"
